# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jason Fitzgerald
email: jason.j.fitzgerald@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am Jason Fitzgerald. I am a Software Engineering student at BYU-I. 
  I love coding, hiking, and traveling. You can usually find me working on 
  a new program, or planning out my next trip. I hope that you enjoy my site!
baseurl: "/jekyll" # the subpath of your site, e.g. /blog
url: "https://jjfitz.github.io" # the base hostname & protocol for your site
twitter_username: jjfitz27
github_username:  jjfitz

# Build settings
markdown: kramdown
